#!/usr/bin/env php

<?php

/*
|--------------------------------------------------------------------------
| Include config file
|--------------------------------------------------------------------------
|
| Jarvis need to include the config's file to work correctly
|
*/

require_once './app/config/config.php';

/*
|--------------------------------------------------------------------------
| Include app´s core
|--------------------------------------------------------------------------
|
| Jarvis need to include the core for work correctly
|
*/

require_once './jarvis_core/app.php';

/*
|--------------------------------------------------------------------------
| Load arguments and iniciate app
|--------------------------------------------------------------------------
|
| Jarvis need to load the arguments passing by console and format it
|
*/

$app = new App($argv);
$_ARGUMENTS = $app->arguments($argv);

/*
|--------------------------------------------------------------------------
| Switch into the different functions to load
|--------------------------------------------------------------------------
|
| Jarvis need to switch the different functions to load it and passing
| parameters
|
*/

switch($_ARGUMENTS['command']) {

    default:

        $app->getCopyritght();
        echo "----------------------------------------------".PHP_EOL;
        echo 'Command not exists or empty, nothing to do.'.PHP_EOL;
        echo 'Have a nice day ;)'.PHP_EOL;
        echo "----------------------------------------------".PHP_EOL.PHP_EOL;

    break;

    case 'create':

        $app->create($_ARGUMENTS['option']);

    break;

    case 'remove':

        $app->remove($_ARGUMENTS['option']);

    break;

}
